### ISSUE TITLE
How to use WebSocket?

### ISSUE THREAD

**Issue by naviDevOnGit** [apollo-server-integrations/apollo-server-integration-next#100]
Unfortunately, the instructions for subscriptions are not transferable for this integration. Are there any instructions how to integrate subscriptions in apollo-server-integration-next? 

https://www.apollographql.com/docs/apollo-server/data/subscriptions/#enabling-subscriptions

**Comment by martinnabhan** [comment]
Unfortunately it's not possible to enable GraphQL subscriptions with this integration since GraphQL subscriptions require a WebSocket server.
