### ISSUE TITLE
how to manipulate response in graphql respolver

### ISSUE THREAD

**Issue by oduncan** [apollo-server-integrations/apollo-server-integration-next#101]
I have a pretty standard api route using the appDir.

`
import { startServerAndCreateNextHandler } from '@as-integrations/next';
import { headers, cookies } from 'next/headers'

// ...

const server = new ApolloServer({
  resolvers,
  typeDefs,
});

const handler = startServerAndCreateNextHandler<NextRequest>(server, { context: async (req) => ({ req, cookies, headers }) });

export async function GET(request: NextRequest) {
  return handler(request);
}

export async function POST(request: NextRequest) {
  return handler(request);
}`

I have no trouble accessing the request and am just placing cookies and headers on the context for testing (I can access them through the requests just fine) I'm just having trouble figuring out how to access the response to do things like set status codes, etc.

Hopefully I'm just missing something simple, thank you for your time.

**Comment by trevor-scheer** [comment]
The context function signature gives you the `reply` object as the second argument (right now you're using `req`).

Apollo Server itself also offers ways to set headers and status codes in the case of error handling.
https://www.apollographql.com/docs/apollo-server/data/errors#setting-http-status-code-and-headers

**Comment by oduncan** [comment]
Thanks, I'll test that. This issue is solved but just so you know that is one of the first things I tried: 

const handler = startServerAndCreateNextHandler(server, { context: async (req, res) => ({ req, res, cookies, headers }) });

in the resolver, res is always undefined, not sure if that's intended.

**Comment by RadoslavMarinov** [comment]
Any example would be great
