### ISSUE TITLE
Wrapper does not pass cookies from the client to the server, making authentication from the server-side impossible

### ISSUE THREAD

**Issue by rafaelsmgomes** [apollo-server-integrations/apollo-server-integration-next#114]
Hi, I've been struggling for a while with something and I have a suspicion that the problem might be that the startServerAndCreateNextHandler function does not pass on the cookies from the client to the backend.

I'm using Next-auth for authentication in the my Nextjs app, and everything works great when I'm making a query from the frontend. But if I try to make a query from the getServerSideProps function I get a "Not Authorized" response from the apollo server. 

Here is my code:

```typescript
const server = new ApolloServer<GraphqlContext>({
  typeDefs: typeDefs,
  resolvers: resolvers,

  introspection: env.NODE_ENV === 'development',
  plugins: [
    responseCachePlugin({}),
  ],
})

const defaultServer = startServerAndCreateNextHandler(server, {
  context: async (req, res) => {
    const session = await getServerSession(req, res, authOptions)
    return { req, res, prisma: prisma, session }
  },
})

export default defaultServer
```
I'm trying to identify the user within the context function by using the req and res that the integration gives me. 

Next-auth uses cookies to authenticate, meaning that because they don't get passed on to the context function, that always returns session null when I'm calling the user from then Server-Side. 

Here is my getServerSideProps function:

```typescript
export async function getServerSideProps(ctx: GetServerSidePropsContext<{}>) {
  const { req, res } = ctx
  console.log('cookies', req.cookies) // prints out cookies from the client
  const session = await getAuthSession({ req, res })
  console.log('GetServerSideProps: ', session) // logs user authenticated

  const apolloClient = initializeApollo({}, { req, res }) // start apollo client and pass req and response to it, I don't think it matters


  const q1 = await apolloClient.query({ query: EXAMPLE_QUERY })
  console.log(q1) // returns an error cause user is Not Authenticated

  return addApolloState(apolloClient, {
    props: { symbol },
  })
}

```

Any feedback is appreciated. At the moment I think my only solution is to recreate the package and add the cookies myself.

**Comment by martinnabhan** [comment]
This integration does pass cookies to Apollo Server. Are you sure your Apollo Client instance on the server side is passing cookies in the request to Apollo Server? You might have to attach the cookies manually server-side like people are doing here: https://github.com/apollographql/apollo-client/issues/4190

**Comment by rafaelsmgomes** [comment]
Oh my, that was spot on!

Immediately solved my problem!

Thank you so much @martinnabhan ! I was struggling with this issue for hours!
