### ISSUE TITLE
API handler should not return a value, received object.

### ISSUE THREAD

**Issue by clement-faure** [apollo-server-integrations/apollo-server-integration-next#116]
Since few days, i've this new warning message showing up in console when graphql api route is called. All still works fine but should i worry about this message ? Thank you in advance !

```
 "@apollo/client": "^3.7.15",
 "@apollo/server": "^4.7.3",
 "@as-integrations/next": "^2.0.0",
 "next": "^13.4.5",
 "react": "^18.2.0",
```

**Comment by martinnabhan** [comment]
If everything works fine I don't think there is anything to worry about, but I will look into this!

**Comment by rishabh-wattoai** [comment]
Any updates to this?

**Comment by simonkberg** [comment]
I believe it's caused by [this line](https://github.com/apollo-server-integrations/apollo-server-integration-next/blob/bb96401deee9c17dce133d20318d006bd51a9d72/src/startServerAndCreateNextHandler.ts#L58); res.end returns the `NextApiResponse`.
This should probably be written as:
```ts
res.end();
return;
