### ISSUE TITLE
How can I set response header using Route Handlers?

### ISSUE THREAD

**Issue by RadoslavMarinov** [apollo-server-integrations/apollo-server-integration-next#118]
I want to be able to set response headers using the Route Handler integration.
I the example I try to access the response object from the context function second argument, but the value is simply `undefined`,

Here is the example: 

```typescript
const server = new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs,
    resolvers: getAllResolvers(),
  }),
});

const handler = startServerAndCreateNextHandler<NextRequest>(
  server,
  {
    context: async (req, res) => {
      console.log(`Response: `, res)
      return {
        req,
        res,
      };
    },
  }
);

export async function POST(request: NextRequest) {
  return handler(request);
}
```
The console output is:

> Response:  undefined

**Comment by martinnabhan** [comment]
Unfortunately due to the way Route Handlers work it's not possible to pass the response object to Apollo Server's context function. What you can do is await the response object from your handler and then modify the response object's headers in the Route Handler like this:
```ts
export async function POST(request: NextRequest) {
  const response = await handler(request);

  response.headers.append('name', 'value');

  return response;
}
```

**Comment by RadoslavMarinov** [comment]
Thank you @martinnabhan for your reply.
That is unfortunate though. There are scenarios where it could be nice to have access to the response inside GQL resolvers the same way we could have access to the request via `context`.

In my case, I would like to be able to set the [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header whereby adding a session token to cookies.

**Comment by martinnabhan** [comment]
Hope you got it working! I think I would to the same workaround.
