### ISSUE TITLE
Wrong type for the startServerAndCreateNextHandler

### ISSUE THREAD

**Issue by Eprince-hub** [apollo-server-integrations/apollo-server-integration-next#121]
The latest Next.js added an optional generic parameter to `NextResponse` according to this PR https://github.com/vercel/next.js/pull/47526/files, but the return type of the the return type for the `startServerAndCreateNextHandler` does not accept generics parameters so `startServerAndCreateNextHandler` function throws a `TS` error when the generic type is provided to the `NextResponse`. 

Code reproduction
I have a code like the one below that would throw a warning because we are enforcing the usage of the generic type on next handlers
```ts
export async function POST(req: NextRequest) {
  return await handler(req);
}
```
So we would have to rewrite the above code to be like the one below, which then throws the error that the type `Response` is not assignable to my `GraphQlRequestBodyType`. The complete error message below

```error
Type 'Response' is not assignable to type 'NextResponse<GraphQlResponseBody>'.ts(2322)
Type 'Response' is not assignable to type 'NextResponse<GraphQlResponseBody>'.
```
```ts
export async function POST(
  req: NextRequest,
): Promise<NextResponse<GraphQlResponseBody>> {
  return await handler(req);
}
```
The error messages can be visualized in the screenshot below.

![Screenshot 2023-06-26 at 16 12 12](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/74430629/4ff45703-c47b-460c-80d0-00e257e2c4c0)

![Screenshot 2023-06-26 at 16 14 41](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/74430629/b1bc2838-1253-4040-91b1-85c5063668ba)

![Screenshot 2023-06-26 at 16 13 27](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/74430629/4c1cf82c-4be7-4b11-aef6-93a25befa1fe)

There is a reproduction on this repository
https://github.com/Eprince-hub/as-integration-next-example

To reproduce
clone the repository
```bash
git clone https://github.com/Eprince-hub/as-integration-next-example.git
```
Install dependencies
```bash
pnpm i
```
Open the `app/api/graphql/route.ts` to see the errors

## What I tried(Currently using this method as a workaround)
Currently, I am using this workaround to suppress the error by wrapping the `startServerAndCreateNextHandler` in my own function, as shown below.

```ts
// My custom type
type GraphQlResponseBody = {
  animal: {
    id: number;
    name: string
   }
}
const handler = async (request: NextRequest) => {
  const response = await startServerAndCreateNextHandler<NextRequest>(
    apolloServer,
    {
      context: async (req) => {
        return { req};
      },
    },
  );

  return new NextResponse<GraphQlResponseBody>((await response(request)).body);
};
```
and I can use it as intended with no problem

```ts
export async function POST(
  req: NextRequest,
): Promise<NextResponse<GraphQlResponseBody>> {
  return await handler(req);
}
```

**Comment by luchillo17** [comment]
I believe this issue might be outdated, been more than 6 months since the last interaction, to begin with, you don't need to await the handler, returning the promise in an async function would already handle the promise the same way, and we now have a typing called `NextApiRequest` instead of the `NextRequest` mentioned here, and it even handles the context headers typings properly.

@Eprince-hub I do think this issue is outdated...

**Comment by martinnabhan** [comment]
Closing as per my comment on #122
