### ISSUE TITLE
Using graphql-ws inside of app router Apollo GraphQL Server

### ISSUE THREAD

**Issue by casperibo** [apollo-server-integrations/apollo-server-integration-next#127]
Hi, I want to use Apollo subscriptions but I couldn't use graphql-ws inside of the Next JS app router.

The example in the Apollo Docs show:

```
// This `app` is the returned value from `express()`.
const httpServer = createServer(app);
```

But there is no express app in the app router as I saw.

It would be awesome to show how to add graphql-ws websocket server in the Next JS App Router Apollo Graphql Server

**Comment by martinnabhan** [comment]
Unfortunately WebSockets aren't supported by Next.js, and thus Apollo Subscriptions can't be used with this integration.
