### ISSUE TITLE
Customize body size limit

### ISSUE THREAD

**Issue by leidsoncruz** [apollo-server-integrations/apollo-server-integration-next#134]
For example, I'm sending a body size greater than 20kB to the Apollo server. The server is not processing, probably due to the body size limit. I already configured the Next api route configuration to increase the body limit but without success.

**Comment by martinnabhan** [comment]
As far as I'm aware there is no body size limit imposed by neither Apollo Server nor this integration. Are you sure it's not Next.js imposing the body size limit?

**Comment by leidsoncruz** [comment]
@martinnabhan thanks for answering.

According to the default NextJS limit, we aren't exceeding it. However, I tried using a configuration with a significantly larger limit and still encountered the same issue.

```
export const config = {
  api: {
    bodyParser: {
      sizeLimit: '100mb',
    },
  },
};
```

![Screenshot 2023-07-25 at 10 04 14](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/1443102/17a55fee-2c8d-4326-a2fe-f8bb3de3dab7)
![Screenshot 2023-07-25 at 10 04 27](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/1443102/4404522c-9118-41e6-9c24-464998a157c2)

The request has been pending indefinitely and has not yet been escalated to the resolver.

**Comment by leidsoncruz** [comment]
I came across a similar problem and was advised to set the bodyParser to false. However, I am currently struggling with parsing to JSON as the Apollo Server v4 does not handle it automatically.

**Comment by trevor-scheer** [comment]
@leidsoncruz can you share a reproduction? <20kb max is surprising.

**Comment by leidsoncruz** [comment]
@trevor-scheer Sure.

server.ts
```
import { ApolloServer } from '@apollo/server';
import { ApolloServerPluginCacheControl } from '@apollo/server/plugin/cacheControl';
import { startServerAndCreateNextHandler } from '@as-integrations/next';
import { GraphQLSchema } from 'graphql/type';
import { getToken } from 'next-auth/jwt';


export const createServer = (schema: GraphQLSchema) =>
  new ApolloServer({
    schema,
    formatError: (formattedError) => ({
      status: formattedError.extensions?.status,
      statusText: formattedError.extensions?.statusText,
      traceId: formattedError.extensions?.traceId,
      code: formattedError.extensions?.code,
      error: formattedError.extensions?.error,
      message: formattedError.message,
    }),
    plugins: [
      ApolloServerPluginCacheControl({ calculateHttpHeaders: false }),
      ...
    ],
  });

export const startServer = () => {
  return startServerAndCreateNextHandler(apolloServer, {
    context: async (req) => {
      const token = await getToken({ req });

      return {
          ....          
        ),
      };
    },
  });
};

export default startServer;
```

pages/api/graphql.ts
```
import { createSchema, createServer, startServer } from 'shared';

import { appConfig } from '../../constants';

const { backendURL } = appConfig;

const schema = createSchema(typeDefs, resolvers);

const apolloServer = createServer(schema);

export default startServer();
```

package.json
```
"@apollo/server": "^4.3.2",
"@as-integrations/next": "^2.0.1",
"next": "12.3.0",
"graphql": "^16.6.0",
```

**Comment by leidsoncruz** [comment]
Upgrading the NextJS package to v12.3.4 fixed the problem. 

https://github.com/vercel/next.js/pull/41270

**Comment by trevor-scheer** [comment]
Thanks for the follow up @leidsoncruz !
