### ISSUE TITLE
Can't contribute.

### ISSUE THREAD

**Issue by YeloPartyHat** [apollo-server-integrations/apollo-server-integration-next#140]
I can't offer pull requests against your repository.

GitHub issue screenshot:
![image](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/34695601/d7cb26c1-ecac-41ab-be4e-5571c096f5ba)

**Comment by martinnabhan** [comment]
Thank you for wanting to contribute! You need to fork the repository and open a pull request from your fork.
