### ISSUE TITLE
POST body missing, invalid Content-Type, or JSON object has no keys.

### ISSUE THREAD

**Issue by tomitrescak** [apollo-server-integrations/apollo-server-integration-next#144]
Hello, I am on Next 13.4.19. The integration fails with error: `POST body missing, invalid Content-Type, or JSON object has no keys.`

Any idea what might be happening?

I found this: "https://github.com/vercel/next.js/discussions/48265" but that does not help (it actually does help to solve the porblem when dealing with apollo-server-micro)

**Comment by trevor-scheer** [comment]
Can you provide more details? A reproduction? Are you setting a content-type header in your request?

**Comment by gauravpanta** [comment]
I am also facing the same issue with nextjs 13. Looks like this module is not respecting `introspection: true` config as well.
The sandbox opens fine but none of the queries are shown.


NExt.js /pages/api/graphql.ts


```
import {
  startServerAndCreateNextHandler
} from "@as-integrations/next";
import {
  ApolloServer
} from "@apollo/server";

const server = new ApolloServer({
  schema,
  introspection: true
});


export default startServerAndCreateNextHandler(server, {
  context: (req, res) => {
    return createContext({
      req,
      res
    })
  },
});
```

Replacing this with apollo standalone server, the graphql server works fine.

**Comment by gauravpanta** [comment]
Turns out it was because i was also exporting config :
```
export const config = {
  api: {
    bodyParser: false
  }
};
```

Removed this and it worked just fine.

**Comment by tomitrescak** [comment]
Same as @gauravpanta

**Comment by trevor-scheer** [comment]
@gauravpanta @tomitrescak is this some common default/pitfall that we should document in the README?

**Comment by tomitrescak** [comment]
@trevor-scheer it will happen to users who are trabnsiting away from `apollo-micro` which would be majority of people as this is the one in the next.js examples from https://github.com/vercel/next.js/tree/canary/examples this is now changed to the new intergration.

Check out this commit:
https://github.com/vercel/next.js/commit/081b8fba67b3b9eac58f07ba1bf2dafd1fdd89cb

Just maybe add it to "warning" if you are upgrading.\ from `apollo-server-micro`
