### ISSUE TITLE
I can't use startServerAndCreateNextHandler when It's deployed on Vercel.

### ISSUE THREAD

**Issue by dduicoder** [apollo-server-integrations/apollo-server-integration-next#153]
```ts
const server = new ApolloServer({
  typeDefs,
  resolvers,
  introspection: true,
});

export default startServerAndCreateNextHandler(server);
```

this is how I defined my server and exported to serverless function via startServerAndCreateNextHandler. This works perfectly fine in my local development environment, but as soon as I deploy it to Vercel it doesn't work.

```ts
import { ApolloClient, InMemoryCache } from "@apollo/client";
const client = new ApolloClient({
  uri: "https://myvercel/api/server",
  cache: new InMemoryCache(),
});

export default client;
```

This is my deployed client.ts code. 

In addition, the error logs from web console and vercel logs were violating CORS, 504 errors from POST method, timeout errors

**Comment by dduicoder** [comment]
`const f = 0;
const y = 0;`

**Comment by dduicoder** [comment]
still not working..

**Comment by martinnabhan** [comment]
Could you provide a reproduction? It's not possible to help you with just the code above.

**Comment by dduicoder** [comment]
@martinnabhan 
```ts
import { ApolloServer } from "@apollo/server";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import { MongoClient } from "mongodb";

const URI = "secret";

const typeDefs = `#graphql
  ...
`;

const resolvers = {
  Query: {
    async getDate(_: any, { date }: any) {
      const client = await MongoClient.connect(URI);
      const db = client.db();
      const datesCollection = db.collection("dates_data");

      const targetDate = await datesCollection.findOne({ date });

      if (targetDate == null) {
        const newDate = {
          date,
          calendars: [],
        };

        await datesCollection.insertOne(newDate);
        client.close();

        return newDate;
      }

      client.close();

      return targetDate;
    },
  },
  Mutation: {
    async addCalendar(
      _: any,
      { date, id, title, start, end, description }: any
    ) {
      const client = await MongoClient.connect(URI);
      const db = client.db();
      const datesCollection = db.collection("dates_data");

      await datesCollection.findOneAndUpdate(
        { date },
        { $push: { calendars: { id, title, start, end, description } as any } }
      );

      client.close();

      return true;
    },
    async removeCalendar(_: any, { date, id }: any) {
      const client = await MongoClient.connect(URI);
      const db = client.db();
      const datesCollection = db.collection("dates_data");

      await datesCollection.findOneAndUpdate(
        { date },
        { $pull: { calendars: { id } as any } }
      );

      client.close();

      return true;
    },
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  introspection: true,
});

export default startServerAndCreateNextHandler(server);
```
Here's my full server code. I think there might be something to do with the mongodb connection.

**Comment by martinnabhan** [comment]
I don't see anything wrong with your code so I also think MongoDB is the culprit. Most probably the connection to your MongoDB instance is timing out.

**Comment by trevor-scheer** [comment]
@dduicoder if this is still an issue for you, we can only help you with a _runnable_ reproduction so that we can trigger the error on our machine. This probably means sharing a repo and a set of instructions for how to setup and recreate the error. I'm going to close this but I'm happy to reopen it if you can provide that for us.

**Comment by dduicoder** [comment]
Hey guys I've solved this problem. Turns out that vercel app uses dynamic IP addresses so I needed to add an exception to access from any IP address in my mongodb server. I've changed the network access in my mongodb atlas and now it's working fine. I truly appreciate your help and support on this! thx
