### ISSUE TITLE
Memory and Performance Metrics

### ISSUE THREAD

**Issue by Miteshdv** [apollo-server-integrations/apollo-server-integration-next#157]
Do we have memory or performance metrics for stand alone apollo server and next server?
Is there way to detect memory usage and leaks for this library ?
Any limitations since there will be 2 node servers running?

**Comment by martinnabhan** [comment]
There is nothing about this library that affects how you measure memory usage/performance or detect memory leaks when using Next.js and Node.js.

This integration doesn't run a separate server from Next.js. It only parses Next.js' incoming request and returns a response. The actual server is run by Node.js.
