### ISSUE TITLE
Next v14 support

### ISSUE THREAD

**Issue by arakelovd** [apollo-server-integrations/apollo-server-integration-next#161]
PR for v14 support: https://github.com/apollo-server-integrations/apollo-server-integration-next/pull/160

**Comment by ccruz2886** [comment]
Hi, @arakelovd Is there any timeline expectation with Next 14 support? eager to use Nextjs with GraphQL, would love to use the latest version for a brand new project. Thanks in advance.

**Comment by arakelovd** [comment]
> Hi, @arakelovd Is there any timeline expectation with Next 14 support? eager to use Nextjs with GraphQL, would love to use the latest version for a brand new project. Thanks in advance.

Currently waiting on @trevor-scheer for a review.

**Comment by martinnabhan** [comment]
Resolved by #160
