### ISSUE TITLE
TypeError: module.require is not a function

### ISSUE THREAD

**Issue by mahesh-rajawat** [apollo-server-integrations/apollo-server-integration-next#172]
When start nextjs with `npm run dev` and reload the api route `http://localhost:3000/api/graphql` 
`
{"errors":[{"message":"module.require is not a function","extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["TypeError: module.require is not a function","    at Module.createHash (/srv/app/.next/server/chunks/node_modules_fb96e5._.js:1658:23)","    at Object.html (/srv/app/.next/server/chunks/node_modules_097efd._.js:241:240)","    at ApolloServer.executeHTTPGraphQLRequest (/srv/app/.next/server/chunks/node_modules_@apollo_server_dist_92ba2d._.js:1905:77)"]}}]}
`

**Comment by martinnabhan** [comment]
Could you please provide a reproduction?

**Comment by mahesh-rajawat** [comment]
Hi @martinnabhan 
To reproduce this, just add `--turbo` in package.json,
` "dev": "next dev --turbo",`
So when i run `npm run dev`, it gives this error.

**Comment by martinnabhan** [comment]
I don't think Apollo Server works with the `--turbo` option so you'll have to use `next dev` instead.

**Comment by Meligy** [comment]
Do we have any idea what's the deal breaker in Turbo Server?

**Comment by joejknowles** [comment]
Ahh, this was hard to find, solves the problem for me too.
