### ISSUE TITLE
Looking for contributors? 

### ISSUE THREAD

**Issue by idoob** [apollo-server-integrations/apollo-server-integration-next#22]
Hi @martinnabhan, It looks like you've made a lot of progress and are close to an initial release. If you're looking for contributors I'm happy to help once you're ready.

**Comment by martinnabhan** [comment]
Thank you for reaching out! I'm still not sure how much work it's going to be to maintain this package but feel free to contribute if there's anything you would like to see added or changed, and if it turns out we need more maintainers I'll be sure to reach out!
