### ISSUE TITLE
apollo server with nextjs 15 turbo pack not working

### ISSUE THREAD

**Issue by ArlieT** [apollo-server-integrations/apollo-server-integration-next#232]
removed this it will work
"dev": "next dev --turbopack",
        
 error:       
        GraphQL Error: {
  message: 'Internal server error',
  extensions: {
    code: 'INTERNAL_SERVER_ERROR',
    stacktrace: [
      'Error: Internal server error',
      '    at internalExecuteOperation (D:\\projects\\sexy-pacers-ecom\\.next\\server\\chunks\\772ed_@apollo_server_dist_3337e0._.js:6470:15)',
      '    at async runHttpQuery (D:\\projects\\sexy-pacers-ecom\\.next\\server\\chunks\\772ed_@apollo_server_dist_3337e0._.js:4826:29)',
      '    at async runPotentiallyBatchedHttpQuery (D:\\projects\\sexy-pacers-ecom\\.next\\server\\chunks\\772ed_@apollo_server_dist_3337e0._.js:5064:16)',
      '    at async ApolloServer.executeHTTPGraphQLRequest (D:\\projects\\sexy-pacers-ecom\\.next\\server\\chunks\\772ed_@apollo_server_dist_3337e0._.js:6375:20)'
    ]
  }

**Comment by ChrisSki** [comment]
Also experiencing this

**Comment by martinnabhan** [comment]
This is an Apollo Server issue and unrelated to this integration.

**Comment by joejknowles** [comment]
@martinnabhan if so, why is there no issue in that repo for this problem?

https://github.com/apollographql/apollo-server/issues?q=turbopack
