### ISSUE TITLE
Tune renovate config

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-next#25]
Might be worth taking some time to tweak the renovate config. Things like scheduling (i.e. once a week) and grouping minor/patch bumps together can go a long way to reduce renovate's noisiness in PRs and commit history.

Happy to open a PR if you're open to what I might come up with, or offer suggestions. Feel free to take inspiration from Apollo Server's renovate config or any of the integrations in this org that use it!

**Comment by martinnabhan** [comment]
Sounds great. I'd be super thankful if you could open a PR!
