### ISSUE TITLE
Add @as-integrations/next to Apollo Server docs

### ISSUE THREAD

**Issue by martinnabhan** [apollo-server-integrations/apollo-server-integration-next#32]
Since we just finished our initial release I would like to add this integration to [Apollo Server docs](https://www.apollographql.com/docs/apollo-server/integrations/integration-index).

Source file is [here](https://github.com/apollographql/apollo-server/blob/main/docs/source/integrations/integration-index.mdx).

**Comment by martinnabhan** [comment]
Pull request opened here: https://github.com/apollographql/apollo-server/pull/7133

**Comment by trevor-scheer** [comment]
Closed via https://github.com/apollographql/apollo-server/pull/7133
