### ISSUE TITLE
Update Next.js examples using Apollo Server 3 to use Apollo Server 4 (and this integration)

### ISSUE THREAD

**Issue by martinnabhan** [apollo-server-integrations/apollo-server-integration-next#33]
There are currently three Next.js examples using Apollo Server:
* [api-routes-apollo-server-and-client-auth](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client-auth/pages/api/graphql.js)
* [api-routes-apollo-server-and-client](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client/pages/api/graphql.js)
* [api-routes-apollo-server](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server/pages/api/graphql.js)

These examples all use Apollo Server 3 with `apollo-server-micro`. I'm thinking we should update these to use Apollo Server 4 (and this integration), making it easier for new users to use Next.js with the latest version of Apollo Server.

Some of these examples are quite old so I'm not sure how much work it's going to be to upgrade them.

**Comment by idoob** [comment]
I'd be happy to submit a CR for this once a release is available. I know there's some [ confusion historically](https://github.com/vercel/next.js/pull/30082) where users have been using `apollo-server-micro` only because that that's what the examples show. This is actually how I found this repo. I was trying to figure out how to run the apollo server 4 with next 🙂.

**Comment by martinnabhan** [comment]
That would be great! I just released v1.0.0 yesterday, and as soon as Next.js 13 support gets merged and released (#34) you should be able to update the Next.js examples to use Apollo Server 4 and this integration without any issues.

**Comment by martinnabhan** [comment]
I've just released #34 so the integration should be compatible with Next.js 13 now!

**Comment by idoob** [comment]
Cool. I've started updating the examples. Will link the PR here within the next day or so.

**Comment by idoob** [comment]
Submitted a PR here : https://github.com/vercel/next.js/pull/42771 . The PR updates all three examples to use latest Apollo Server 4, @as-integrations/next, and to use TypeScript.

**Comment by ScottAwesome** [comment]
It would also be useful to test this against the new edge-runtime, which is sure to be the future going forward soon enough I think

**Comment by martinnabhan** [comment]
https://github.com/vercel/next.js/pull/42771 got merged so I'm closing this.
Awesome work @idoob, thank you!

**Comment by trevor-scheer** [comment]
Thanks for your work on this @idoob!
