### ISSUE TITLE
Request Issue

### ISSUE THREAD

**Issue by stephenasuncionDEV** [apollo-server-integrations/apollo-server-integration-next#53]
Hello,

I am getting `POST body missing, invalid Content-Type, or JSON object has no keys.` error when requesting. 
I am using `application/json` for Content-Type header

Error:
![image](https://user-images.githubusercontent.com/73958774/205263819-69dc9c49-282a-4f61-bade-4d47931f1c30.png)

Code:
![image](https://user-images.githubusercontent.com/73958774/205264153-324b8cb9-f0d7-48a5-9569-39ae8c2a4ce3.png)

**Comment by martinnabhan** [comment]
This integration doesn't require you to disable Next.js' built in body parser.

Removing the following should fix your issue:
```ts
export const config: PageConfig = {
  api: {
    bodyParser: false,
  },
};
```

**Comment by stephenasuncionDEV** [comment]
That worked! Thanks @martinnabhan .
