### ISSUE TITLE
Cors and upload file

### ISSUE THREAD

**Issue by javiash** [apollo-server-integrations/apollo-server-integration-next#59]
Hi! I'm using this integration and is working alright but when I try to use the apollo playground it can't connect and when I try to test the endpoint this is the response 
![image](https://user-images.githubusercontent.com/46492315/208726854-69d2193b-4054-4b26-9444-a699a6a0b0bd.png)

Also, I would like to upload image file with the graphql-upload npm package, also successfully, saying that the the form ended unexpectedly, like if it isn't waiting for the process to finish.

This is my code: 

```
import connectDb from './mongoose.config';
import resolvers from './resolvers';
import typeDefs from './schemas';

import { getToken } from 'next-auth/jwt';

import { ApolloServer } from '@apollo/server';
import { startServerAndCreateNextHandler } from '@as-integrations/next';
import processRequest from 'graphql-upload/processRequest.mjs';

connectDb();

const server = new ApolloServer({
  resolvers,
  typeDefs,
});

export default startServerAndCreateNextHandler(server, {
  context: async (req, res) => {
    const contentType = req.headers['content-type'];
    console.log(
      '🚀 ~ file: graphql.ts ~ line 22 ~ context: ~ contentType',
      contentType
    );

    if (contentType && contentType.indexOf('multipart/form-data') > -1) {
      try {
        req.body = await processRequest(req, res);
      } catch (error) {
        console.log('🚀 ~ file: graphql.ts:37 ~ context: ~ error', error);
        return { req, res, user: await getToken({ req }) };
      }
    }
    return { req, res, user: await getToken({ req }) };
  },
});

```

For this reason I'm still using apollo server micro, but would like to upgrade to apollo server v4.

Thanks!

**Comment by trevor-scheer** [comment]
@javiash thanks for the code snippet but if you're able to provide a runnable reproduction that would speed up the process here. I'm not a next expert so setting up a next project would probably take me awhile (though @martinnabhan might have less trouble than I!)

**Comment by javiash** [comment]
Hi! I've never used codesandbox, but I think I could replicate my case succesfully.

https://codesandbox.io/p/sandbox/dark-feather-1pi4mh

**Comment by martinnabhan** [comment]
@javiash thank you for the reproduction!

Did you get Apollo Sandbox working?
It seems to works fine in the reproduction you provided.

As for `graphql-upload`, you'll probably have to process `req` before passing it to Apollo Server like this:
```ts
import { ApolloServer } from "@apollo/server";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import processRequest from "graphql-upload/processRequest.mjs";

const server = new ApolloServer({
  resolvers,
  typeDefs,
});

const handler = startServerAndCreateNextHandler(server);

const graphql = async (req, res) => {
  const contentType = req.headers["content-type"];

  if (contentType && contentType.indexOf("multipart/form-data") > -1) {
    req.body = await processRequest(req, res);
  }

  await handler(req, res);
};

export default graphql;
```

This works, but gives me a different error, "Unexpected end of form", which I haven't been able to solve yet but I'll see what I can do the coming days!

**Comment by javiash** [comment]
Hi! Apollo sandbox isn't working for me, even with your  changes.

And the error "Unexpected end of form" is the same one I'm getting. I believe that this is responsible for that error

`Promisify and await file upload streams in resolvers or the server will send a response to the client before uploads are complete, causing a disconnect.`

This is from the Tips in the graphql-upload git repo https://github.com/jaydenseric/graphql-upload

**Comment by martinnabhan** [comment]
I got file uploads working here: https://codesandbox.io/p/sandbox/wispy-mountain-rnk731

Next.js uses `body-parser` to parse API route requests by default, which unfortunately doesn't support multipart requests, causing the "Unexpected end of form" error.

If we disable `body-parser` for the API route we can process multipart requests using `graphql-upload`'s `processRequest`, but this causes JSON requests to fail (as they won't be parsed).

To work around this we can check if the request is a multipart request, and if it is we use `graphql-upload`'s `processRequest` to parse the request. If it is not we use Next.js's `parseBody` function to parse the request as Next.js would normally do.

The important parts:
```ts
...

import processRequest from "graphql-upload/processRequest.mjs";
import { parseBody } from 'next/dist/server/api-utils/node'; // Next.js uses this function to parse requests if body-parser isn't disabled

export const config = {
  api: {
    bodyParser: false, // disable body-parser
  },
};

...

const handler = startServerAndCreateNextHandler(server);

const graphql = async (req, res) => {
  const contentType = req.headers["content-type"];

  if (contentType && contentType.indexOf("multipart/form-data") > -1) {
    req.body = await processRequest(req, res); // parse multipart requests with graphql-upload
  } else {
    req.body = await parseBody(req); // parse any other requests with body-parser
  }

  return await handler(req, res);
};

export default graphql;
```

**Comment by javiash** [comment]
That's obsoletely awesome!! It's working perfectly!!! Thank you very, very much!! 

Do you know what should it be used as a second parameter for the parseBody function? Typescript is telling me that parameter limit is missing. For now I added an empty string and it's working...

Also, sorry to keep on asking, apollo playground isn't working, still with Cors issues...

```⚠️ The [startStandaloneServer](https://www.apollographql.com/docs/apollo-server/api/standalone) function's CORS behavior is unalterable. To pass credentials via cookies, you must first swap to another Apollo Server integration.```

By looking at the official documentation, I can't change the CORS configuration unless using an Express server. I'm using cookies credentials with Next-Auth, so that is a something to take into account 

https://www.apollographql.com/docs/apollo-server/security/cors/#passing-credentials-with-cors

I'm not new with this issues, I could configure everything using apollo server 3, but apollo server 4 has this "breaking" changes...

Again, thanks!

**Comment by martinnabhan** [comment]
Glad you got it working!

The limit parameter is `1mb` by default, but can be changed to fit your needs:
https://nextjs.org/docs/api-routes/request-helpers#custom-config

There are many ways to enable CORS in a Next.js API route.
You can use the popular [nextjs-cors](https://github.com/yonycalsin/nextjs-cors#usage) package:
```ts
...

import { NextApiHandler, NextApiRequest, NextApiResponse } from 'next';

...

const server = new ApolloServer({
  resolvers,
  typeDefs,
});

const handler = startServerAndCreateNextHandler(server);

const graphql: NextApiHandler = async (req, res) => {
  await NextCors(req, res, {
    methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
    origin: '*',
  });

  await handler(req, res);
};

export default graphql;
```

Or you can write the middleware yourself as is shown in [Next.js' CORS example](https://github.com/vercel/next.js/blob/canary/examples/api-routes-cors/pages/api/cors.ts):
```ts
...

import Cors from 'cors';

...

function runMiddleware(req: NextApiRequest, res: NextApiResponse, fn: Function) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result: any) => {
      if (result instanceof Error) {
        return reject(result);
      }

      return resolve(result);
    });
  });
}

...

const server = new ApolloServer({
  resolvers,
  typeDefs,
});

const handler = startServerAndCreateNextHandler(server);

const graphql: NextApiHandler = async (req, res) => {
  await runMiddleware(req, res, cors);
  await handler(req, res);
};

export default graphql;
```

Or you can set the CORS headers explicitly as shown in [Vercel's documentation](https://vercel.com/guides/how-to-enable-cors#enabling-cors-in-a-single-node.js-serverless-function):
```ts
...

const handler = startServerAndCreateNextHandler(server);

const graphql: NextApiHandler = async (req, res) => {
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', '*');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
  }

  await handler(req, res);
};

export default graphql;
```

Or you can add the headers using `next.config.js`:
```ts
module.exports = {
  async headers() {
    return [
      {
        source: "/api/graphql",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
          { key: "Access-Control-Allow-Headers", value: "*" },
        ]
      }
    ]
  }
};
```

Please let me know if this works for you (and be careful with allowing any header or origin)!

**Comment by javiash** [comment]
Sorry the late response, I was checking everything was working and I can happily say that it is working wonderful. For cors I went with [NextJs CORS example](https://github.com/vercel/next.js/blob/canary/examples/api-routes-cors/pages/api/cors.ts). 

I believe that we can close this issue, and I hope that it will help anybody else facing this.
