### ISSUE TITLE
Code Explanation in README

### ISSUE THREAD

**Issue by wakywayne** [apollo-server-integrations/apollo-server-integration-next#66]
This code seems pretty lightweight, I think it would be worth it to include a brief overview of how the code works at the end of the readme for people who are interested. Thanks for taking the time to make this for nextJS 😁😁😁

**Comment by martinnabhan** [comment]
Thank you for the suggestion! The code largely follows the [very thorough guide](https://www.apollographql.com/docs/apollo-server/integrations/building-integrations) in the official Apollo Docs which I believe explains the inner workings of an integration far better than I could. However if more Next.js-centric code will need to be added in the future I agree an overview might be helpful.
