### ISSUE TITLE
i am used apollo server 4 with this integration but i have this error

### ISSUE THREAD

**Issue by edw19** [apollo-server-integrations/apollo-server-integration-next#71]
![image](https://user-images.githubusercontent.com/47750859/217376836-08cd77f4-bb47-44c5-8707-e898ecd75ab5.png)

and the sandbox dont load the queries

![image](https://user-images.githubusercontent.com/47750859/217376997-0868ce3d-bf01-4eb4-91e9-58147c60f960.png)

can i help me ?

**Comment by edw19** [comment]
![image](https://user-images.githubusercontent.com/47750859/217377143-ca5bdaa1-dd9d-436a-a372-10e864fae4d4.png)

use the command to found the problem, but i dont have idea of how implements cors

**Comment by martinnabhan** [comment]
Please refer to my comment [here](https://github.com/apollo-server-integrations/apollo-server-integration-next/issues/59#issuecomment-1365618731) on how to implement CORS.

**Comment by edw19** [comment]
nice cors is enabled but now i have another error 🤔

![image](https://user-images.githubusercontent.com/47750859/217688453-4f0ebcf2-8f43-4678-bfb5-a8d53f55ca4c.png)

**Comment by martinnabhan** [comment]
Could you please share the code from your API route? Or preferably a reproduction?

**Comment by edw19** [comment]
import "reflect-metadata";
import { NextApiHandler } from 'next';
import NextCors from "nextjs-cors";
import { ApolloServer } from '@apollo/server';
import { startServerAndCreateNextHandler } from '@as-integrations/next';
import { getToken } from 'next-auth/jwt';
import { MyContext } from 'server/@types/MyContext';
import { createSchema } from 'server/graphql/createSchema';
import { CashierService } from 'server/modules/cashiers/services/cashier.service';
import { CompanyModel } from 'server/modules/companies/entities';
import { EstablishmentService } from 'server/modules/establishments/establishment.service';
import { UsersService } from 'server/modules/users/services/users.service';
import { createConnection } from 'server/utils/createConnection';
import { ApolloServerPluginLandingPageGraphQLPlayground } from '@apollo/server-plugin-landing-page-graphql-playground';

const server = new ApolloServer<MyContext>({
    schema: createSchema(),
    plugins: [ApolloServerPluginLandingPageGraphQLPlayground()]
});

const handler = startServerAndCreateNextHandler(server, {
    context: async (req, res) => {

        if (req?.cookies?.ssr || Object.keys(req.cookies).length === 0) {
            const cookies = JSON.parse(req.headers.cookie!);
            req.cookies = cookies;
        }

        await createConnection()

        const token = await getToken({ req, secret: "my-super-secret-key" })

        if (token) {
            const userId: any = token.sub;
            const currentUser = await UsersService.getUser(userId);
            // if user is a cashier
            if (currentUser && currentUser.role.includes("USER-CASHIER")) {
                req.user = { id: currentUser.id };
                req.company = { id: currentUser.company! };
                req.establishment = { id: currentUser.establishment! };
                req.cashier = { id: currentUser.cashier! };
            } else {

                const company = await CompanyModel.findOne({ userOwner: userId })
                const establishment = await EstablishmentService.getMainEstablishment(company!.id)
                const cashier = await CashierService.getCashierByUserId(userId);

                if (userId && company && establishment && cashier) {
                    req.user = { id: userId };
                    req.company = { id: company.id };
                    req.establishment = { id: establishment.id };
                    req.cashier = { id: cashier.id };
                }
            }
        }
        return { req, res };
    },
})


const graphql: NextApiHandler = async (req, res) => {
    await NextCors(req, res, {
        methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
        origin: '*',
    });

    await handler(req, res);
};

export default graphql;

this is the the code for api route

**Comment by edw19** [comment]
thanks your aswear is correct the error was in my config cookies
