### ISSUE TITLE
Not supported in next js 13.2

### ISSUE THREAD

**Issue by RajaARK99** [apollo-server-integrations/apollo-server-integration-next#77]
Can anyone show me how to connect next js 13.2 route.ts setup

**Comment by martinnabhan** [comment]
I haven't tested the new Route Handlers feature yet, but I'll try to take a look this week!

**Comment by rodydavis** [comment]
Also curious how to use in route handlers (new app directory), and also trying to add it in the pages directory too but not finding the correct route.

**Comment by martinnabhan** [comment]
I tried out the new Route Handlers feature, and turns out it will take a bit of work to support them. I've created an issue [here](#79) and will try to get an update out soon!
