### ISSUE TITLE
Support Next.js Route Handlers

### ISSUE THREAD

**Issue by martinnabhan** [apollo-server-integrations/apollo-server-integration-next#79]
Next.js 13.2 introduced a new way of creating API routes using a feature called [Route Handlers](https://beta.nextjs.org/docs/routing/route-handlers).

Route Handlers use the native `Request` and `Response` objects, or Next.js' new `NextRequest` and `NextResponse` objects, which have a fairly different API compared to the old `NextApiRequest` and `NextApiResponse` objects, in turn making them incompatible with this integration.

Supporting these new objects does seem simple enough, but I'm not sure yet if we should make `startServerAndCreateNextHandler` work with the new objects, or if it would be better to create a separate handler just for them.

First I'll try to get Route Handlers working and then I'll see how supporting both API Routes and Route Handlers in the same handler function will impact code readability.

**Comment by karlhorky** [comment]
Thanks @martinnabhan ! 🙌 We will try it out in our next cohort of bootcamp students.
