### ISSUE TITLE
CORS headers?

### ISSUE THREAD

**Issue by elmarsto** [apollo-server-integrations/apollo-server-integration-next#94]
Hi! I'm having some trouble with an Apollo Client / Apollo Server pair under NextJS 13 (app dir enabled.)

The project is at https://github.com/elmarsto/substrate.git

Basically, 

 - server-side rendering is straightforwardly busted, because CORS headers aren't sent
 - even client-side rendering ('use client' etc) is busted, at least on localhost. 

So, for now, I want to use `Access-Control-Allow-Origin: *`. 

How do I do this? Do I follow e.g. https://beta.nextjs.org/docs/routing/route-handlers#headers  (doing things the NextJS way) or do I do something along the lines of https://www.apollographql.com/docs/apollo-server/security/cors (but this documentation is for Express, not NextJS?)

How do I set this header using `apollo-server-integration-next`?  An example in the docs would be amazing. 

TYSM for an amazing product

**Comment by elmarsto** [comment]
Bonus points for showing how to disable CORS entirely for server-side queries

**Comment by elmarsto** [comment]
For context, I found this, but I'm not sure how to apply it for `appDir` and `apollo-server-integration-next` https://github.com/apollographql/apollo-server/issues/4779

**Comment by fullgream** [comment]
I join in the question. You can't pass the `res` parameter to the context, and because of that you can't set the right headers in resolvers. Or did I miss something?

**Comment by elmarsto** [comment]
Yeah precisely. TBH this seems like a pretty full-stop problem to using Apollo Server with NextJS AppDir. I wish I'd known before I implemented.

**Comment by trevor-scheer** [comment]
My recommendation would be to take the CORS approach [recommended by Next](https://beta.nextjs.org/docs/routing/route-handlers#cors).

Also, if you're using `appDir` I think you _do_ get a handle on the response object in your context function as shown here:
https://github.com/apollo-server-integrations/apollo-server-integration-next/blob/main/src/startServerAndCreateNextHandler.ts#L30

So if you wanted to set your CORS headers in the context function you should be able to like so:
```ts
startServerAndCreateNextHandler(server, {
  context: async (_req, res) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.setHeader("Access-Control-Allow-Credentials", "true");
    return {};
  }
});
```

Is that helpful?

**Comment by martinnabhan** [comment]
Unfortunately when using `appDir` the `Response` object is instantiated after Apollo Server execution ends (since you can't set the body of a `Response` object after instantiation), which means we can't pass it to the context.

However you can set CORS headers after receiving the response object from the integration:
```ts
export async function GET(request: NextRequest) {
  const response = await handler(request);

  response.headers.set("Access-Control-Allow-Origin", "*");
  response.headers.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  response.headers.set("Access-Control-Allow-Headers", "Content-Type, Authorization");
  response.headers.set("Access-Control-Allow-Credentials", "true");

  return response;
}
```

**Comment by elmarsto** [comment]
Amazing thank you so much~!
